package com.hdu.common;

import java.util.HashMap;
import java.util.Map;

/**
 * author wujun
 */
public class CTokens {

    // 关键字
    public static final byte AUTO = 0;
    public static final byte BREAK = 1;
    public static final byte CASE = 2;
    public static final byte CHAR = 3;
    public static final byte CONST = 4;
    public static final byte CONTINUE = 5;
    public static final byte DEFAULT = 6;
    public static final byte DO = 7;
    public static final byte DOUBLE = 8;
    public static final byte ELSE = 9;
    public static final byte ENUM = 10;
    public static final byte EXTERN = 11;
    public static final byte FLOAT = 12;
    public static final byte FOR = 13;
    public static final byte GOTO = 14;
    public static final byte IF = 15;
    public static final byte INLINE = 16;
    public static final byte INT = 17;
    public static final byte LONG = 18;
    public static final byte REGISTER = 19;
    public static final byte RESTRICT = 20;
    public static final byte RETURN = 21;
    public static final byte SHORT = 22;
    public static final byte SIGNED = 23;
    public static final byte SIZE_OF = 24;
    public static final byte STATIC = 25;
    public static final byte STRUCT = 26;
    public static final byte SWITCH = 27;
    public static final byte TYPE_OF = 28;
    public static final byte UNION = 29;
    public static final byte UNSIGNED = 30;
    public static final byte VOID = 31;
    public static final byte VOLATILE = 32;
    public static final byte WHILE = 33;
    public static final byte ALIGN_AS = 34;
    public static final byte ALIGN_OF = 35;
    public static final byte AUTOMIC = 36;
    public static final byte BOOL = 37;
    public static final byte COMPLEX = 38;
    public static final byte GENERIC = 39;
    //public static final byte IMAGINARY = 40;
    //public static final byte NO_RETURN = 41;
    public static final byte STATIC_ASSERT = 42;
    public static final byte THREAD_LOCAL = 43;
    public static final byte LEFT_PAREN = 44;
    public static final byte RIGHT_PAREN = 45;
    public static final byte LEFT_BRACKET = 46;
    public static final byte RIGHT_BRACKET = 47;
    public static final byte LEFT_BRACE = 48;
    public static final byte RIGHT_BRACE = 49;
    public static final byte LESS = 50;
    public static final byte LESS_EQUAL = 51;
    public static final byte GREATER = 52;
    public static final byte GREATER_EQUAL = 53;
    public static final byte LEFT_SHIFT = 54;
    public static final byte RIGHT_SHIFT = 55;
    public static final byte PLUS = 56;
    public static final byte PLUS_PLUS = 57;
    public static final byte MINUS = 58;
    public static final byte MINUS_MINUS = 59;
    public static final byte STAR = 60;
    public static final byte DIV = 61;
    public static final byte MOD = 62;
    public static final byte AND = 63;
    public static final byte OR = 64;
    public static final byte AND_AND = 65;
    public static final byte OR_OR = 66;
    public static final byte CARET = 67;
    public static final byte NOT = 68;
    public static final byte TILDE = 69;
    public static final byte QUESTION = 70;
    public static final byte COLON = 71;
    public static final byte SEMI = 72;
    public static final byte COMMA = 73;
    public static final byte ASSIGN = 74;
    public static final byte STAR_ASSIGN = 75;
    public static final byte DIV_ASSIGN = 76;
    public static final byte MOD_ASSIGN = 77;
    public static final byte PLUS_ASSIGN = 78;
    public static final byte MINUS_ASSIGN = 79;
    public static final byte LEFT_SHIFT_ASSIGN = 80;
    public static final byte RIGHT_SHIFT_ASSIGN = 81;
    public static final byte AND_ASSIGN = 82;
    public static final byte XOR_ASSIGN = 83;
    public static final byte OR_ASSIGN = 84;
    public static final byte EQUAL = 85;
    public static final byte NOT_EQUAL = 86;
    public static final byte ARROW = 87;
    public static final byte DOT = 88;
    public static final byte ELLIPSIS = 89;
    public static final byte IDENTIFIER = 90;
    public static final byte DIGIT = 91;
    public static final byte POUND = 92;

    public static final byte BOUND_LEFT = 40;
    public static final byte BOUND_RIGHT = 41;

    public static final String KEY_WORDs_WITH_PAREN = "for,switch,if,while";

    public static Map<String, Byte> tokenMap = new HashMap<>();

    static {
        tokenMap.put("auto", AUTO);
        tokenMap.put("break", BREAK);
        tokenMap.put("case", CASE);
        tokenMap.put("char", CHAR);
        tokenMap.put("const", CONST);
        tokenMap.put("continue", CONTINUE);
        tokenMap.put("default", DEFAULT);
        tokenMap.put("do", DO);
        tokenMap.put("double", DOUBLE);
        tokenMap.put("else", ELSE);
        tokenMap.put("enum", ENUM);
        tokenMap.put("extern", EXTERN);
        tokenMap.put("float", FLOAT);
        tokenMap.put("for", FOR);
        tokenMap.put("goto", GOTO);
        tokenMap.put("if", IF);
        tokenMap.put("inline", INLINE);
        tokenMap.put("int", INT);
        tokenMap.put("long", LONG);
        tokenMap.put("register", REGISTER);
        tokenMap.put("restrict", RESTRICT);
        tokenMap.put("return", RETURN);
        tokenMap.put("short", SHORT);
        tokenMap.put("signed", SIGNED);
        tokenMap.put("sizeof", SIZE_OF);
        tokenMap.put("static", STATIC);
        tokenMap.put("struct", STRUCT);
        tokenMap.put("switch", SWITCH);
        tokenMap.put("typeof", TYPE_OF);
        tokenMap.put("union", UNION);
        tokenMap.put("unsigned", UNSIGNED);
        tokenMap.put("void", VOID);
        tokenMap.put("volatile", VOLATILE);
        tokenMap.put("while", WHILE);
        tokenMap.put("_Alignas", ALIGN_AS);
        tokenMap.put("_Alignof", ALIGN_OF);
        tokenMap.put("_Automic", AUTOMIC);
        tokenMap.put("_Bool", BOOL);
        tokenMap.put("_Complex", COMPLEX);
        tokenMap.put("_Generic", GENERIC);
        //tokenMap.put("_Imaginary", IMAGINARY);
        //tokenMap.put("_Noreturn", NO_RETURN);
        tokenMap.put("_Static_Assert", STATIC_ASSERT);
        tokenMap.put("_Thread_Local", THREAD_LOCAL);
        tokenMap.put("(", LEFT_PAREN);
        tokenMap.put(")", RIGHT_PAREN);
        tokenMap.put("[", LEFT_BRACKET);
        tokenMap.put("]", RIGHT_BRACKET);
        tokenMap.put("{", LEFT_BRACE);
        tokenMap.put("}", RIGHT_BRACE);
        tokenMap.put("<", LESS);
        tokenMap.put("<=", LESS_EQUAL);
        tokenMap.put(">", GREATER);
        tokenMap.put(">=", GREATER_EQUAL);
        tokenMap.put("<<", LEFT_SHIFT);
        tokenMap.put(">>", RIGHT_SHIFT);
        tokenMap.put("+", PLUS);
        tokenMap.put("++", PLUS_PLUS);
        tokenMap.put("-", MINUS);
        tokenMap.put("--", MINUS_MINUS);
        tokenMap.put("*", STAR);
        tokenMap.put("/", DIV);
        tokenMap.put("%", MOD);
        tokenMap.put("&", AND);
        tokenMap.put("|", OR);
        tokenMap.put("&&", AND_AND);
        tokenMap.put("||", OR_OR);
        tokenMap.put("^", CARET);
        tokenMap.put("!", NOT);
        tokenMap.put("~", TILDE);
        tokenMap.put("?", QUESTION);
        tokenMap.put(":", COLON);
        tokenMap.put(";", SEMI);
        tokenMap.put(",", COMMA);
        tokenMap.put("=", ASSIGN);
        tokenMap.put("*=", STAR_ASSIGN);
        tokenMap.put("/=", DIV_ASSIGN);
        tokenMap.put("%=", MOD_ASSIGN);
        tokenMap.put("+=", PLUS_ASSIGN);
        tokenMap.put("-=", MINUS_ASSIGN);
        tokenMap.put("<<=", LEFT_SHIFT_ASSIGN);
        tokenMap.put(">>=", RIGHT_SHIFT_ASSIGN);
        tokenMap.put("&=", AND_ASSIGN);
        tokenMap.put("^=", XOR_ASSIGN);
        tokenMap.put("|=", OR_ASSIGN);
        tokenMap.put("==", EQUAL);
        tokenMap.put("!=", NOT_EQUAL);
        tokenMap.put("->", ARROW);
        tokenMap.put(".", DOT);
        tokenMap.put("...", ELLIPSIS);
        tokenMap.put("id", IDENTIFIER);
        tokenMap.put("digit", DIGIT);
        tokenMap.put("#", POUND);
    }
}
