package com.hdu.common;

import java.util.HashMap;
import java.util.Map;

public class JSTokens {

    public static final byte ID = 0;
    public static final byte DIGIT = 1;
    public static final byte ABSTRACT = 2;
    public static final byte ARGUMENTS = 3;
    public static final byte BOOLEAN = 4;
    public static final byte BREAK = 5;
    public static final byte BYTE = 6;
    public static final byte CASE = 7;
    public static final byte CATCH = 8;
    public static final byte CHAR = 9;
    public static final byte CLASS = 10;
    public static final byte CONST = 11;
    public static final byte CONTINUE = 12;
    public static final byte DEBUGGER = 13;
    public static final byte DEFAULT = 14;
    public static final byte DELETE = 15;
    public static final byte DO = 16;
    public static final byte DOUBLE = 17;
    public static final byte ELSE = 18;
    public static final byte ENUM = 19;
    public static final byte EVAL = 20;
    public static final byte EXPORT = 21;
    public static final byte EXTENDS = 22;
    public static final byte FALSE = 23;
    public static final byte FINAL = 24;
    public static final byte FINALLY = 25;
    public static final byte FLOAT = 26;
    public static final byte FOR = 27;
    public static final byte FUNCTION = 28;
    public static final byte GOTO = 29;
    public static final byte IF = 30;
    public static final byte IMPLEMENTS = 31;
    public static final byte IMPORT = 32;
    public static final byte IN = 33;
    public static final byte INSTANCE_OF = 34;
    public static final byte INT = 35;
    public static final byte INTERFACE = 36;
    public static final byte LET = 37;
    public static final byte LONG  = 38;
    public static final byte NATIVE = 39;

    public static final byte BOUND_LEFT = 40;
    public static final byte BOUND_RIGHT = 41;

    public static final byte NEW = 42;
    public static final byte NULL = 43;
    public static final byte PACKAGE = 44;
    public static final byte PRIVATE = 45;
    public static final byte PROTECTED = 46;
    public static final byte PUBLIC = 47;
    public static final byte RETURN = 48;
    public static final byte SHORT = 49;
    public static final byte STATIC = 50;
    public static final byte SUPER = 51;
    public static final byte SWITCH = 52;
    public static final byte SYNCHRONIZED = 53;
    public static final byte THIS = 54;
    public static final byte THROW = 55;
    public static final byte THROWS = 56;
    public static final byte TRANSIENT = 57;
    public static final byte TRUE = 58;
    public static final byte TRY = 59;
    public static final byte TYPE_OF = 60;
    public static final byte VAR = 61;
    public static final byte VOID = 62;
    public static final byte VOLATILE = 63;
    public static final byte WHILE = 64;
    public static final byte WITH = 65;
    public static final byte YIELD = 66;
    public static final byte PLUS = 67;
    public static final byte MINUS = 68;
    public static final byte STAR = 69;
    public static final byte DIV = 70;
    public static final byte MOD = 71;
    public static final byte PLUS_PLUS = 72;
    public static final byte MINUS_MINUS = 73;
    public static final byte ASSIGN = 74;
    public static final byte PLUS_ASSIGN = 75;
    public static final byte MINUS_ASSIGN = 76;
    public static final byte STAR_ASSIGN = 77;
    public static final byte DIV_ASSIGN = 78;
    public static final byte MOD_ASSIGN = 79;
    public static final byte EQUAL = 80;
    public static final byte ABSOLUTE_EQUAL = 81;
    public static final byte NOT_EQUAL = 82;
    public static final byte ABSOLUTE_NOT_EQUAL = 83;
    public static final byte GREATER = 84;
    public static final byte LESS = 85;
    public static final byte GREATER_EQUAL = 86;
    public static final byte LESS_EQUAL = 87;
    public static final byte AND = 88;
    public static final byte OR = 89;
    public static final byte NOT = 90;
    public static final byte QUESTION = 91;
    public static final byte COLON = 92;
    public static final byte SEMI = 93;
    public static final byte COMMA = 94;
    public static final byte DOT = 95;
    public static final byte LEFT_SMALL_BRACKET = 96;
    public static final byte LEFT_MID_BRACKET = 97;
    public static final byte LEFT_LARGE_BRACKET = 98;
    public static final byte RIGHT_SMALL_BRACKET = 99;
    public static final byte RIGHT_MID_BRACKET = 100;
    public static final byte RIGHT_LARGE_BRACKET = 101;


    public static final String KEY_WORDs_WITH_PAREN = "for,switch,catch,if,while";

    public static Map<String, Byte> tokenMap = new HashMap<>();
    static {
        tokenMap.put("abstract", ABSTRACT);
        tokenMap.put("arguments", ARGUMENTS);
        tokenMap.put("boolean", BOOLEAN);
        tokenMap.put("break", BREAK);
        tokenMap.put("byte", BYTE);
        tokenMap.put("case", CASE);
        tokenMap.put("catch", CATCH);
        tokenMap.put("char", CHAR);
        tokenMap.put("class", CLASS);
        tokenMap.put("const", CONST);
        tokenMap.put("continue", CONTINUE);
        tokenMap.put("debugger", DEBUGGER);
        tokenMap.put("default", DEFAULT);
        tokenMap.put("delete", DELETE);
        tokenMap.put("do", DO);
        tokenMap.put("double", DOUBLE);
        tokenMap.put("else", ELSE);
        tokenMap.put("enum", ENUM);
        tokenMap.put("eval", EVAL);
        tokenMap.put("export", EXPORT);
        tokenMap.put("extends", EXTENDS);
        tokenMap.put("false", FALSE);
        tokenMap.put("final", FINAL);
        tokenMap.put("finally", FINALLY);
        tokenMap.put("float", FLOAT);
        tokenMap.put("for", FOR);
        tokenMap.put("function", FUNCTION);
        tokenMap.put("goto", GOTO);
        tokenMap.put("if", IF);
        tokenMap.put("implements", IMPLEMENTS);
        tokenMap.put("import", IMPORT);
        tokenMap.put("in", IN);
        tokenMap.put("instanceof", INSTANCE_OF);
        tokenMap.put("int", INT);
        tokenMap.put("interface", INTERFACE);
        tokenMap.put("let", LET);
        tokenMap.put("long", LONG);
        tokenMap.put("native", NATIVE);
        tokenMap.put("new", NEW);
        tokenMap.put("null", NULL);
        tokenMap.put("package", PACKAGE);
        tokenMap.put("private", PRIVATE);
        tokenMap.put("protected", PROTECTED);
        tokenMap.put("public", PUBLIC);
        tokenMap.put("return", RETURN);
        tokenMap.put("short", SHORT);
        tokenMap.put("static", STATIC);
        tokenMap.put("super", SUPER);
        tokenMap.put("switch", SWITCH);
        tokenMap.put("synchronized", SYNCHRONIZED);
        tokenMap.put("this", THIS);
        tokenMap.put("throw", THROW);
        tokenMap.put("throws", THROWS);
        tokenMap.put("transient", TRANSIENT);
        tokenMap.put("true", TRUE);
        tokenMap.put("try", TRY);
        tokenMap.put("typeof", TYPE_OF);
        tokenMap.put("var", VAR);
        tokenMap.put("void", VOID);
        tokenMap.put("volatile", VOLATILE);
        tokenMap.put("while", WHILE);
        tokenMap.put("with", WITH);
        tokenMap.put("yield", YIELD);
        tokenMap.put("+", PLUS);
        tokenMap.put("-", MINUS);
        tokenMap.put("*", STAR);
        tokenMap.put("/", DIV);
        tokenMap.put("%", MOD);
        tokenMap.put("++", PLUS_PLUS);
        tokenMap.put("--", MINUS_MINUS);
        tokenMap.put("=", ASSIGN);
        tokenMap.put("+=", PLUS_ASSIGN);
        tokenMap.put("-=", MINUS_ASSIGN);
        tokenMap.put("*=", STAR_ASSIGN);
        tokenMap.put("/=", DIV_ASSIGN);
        tokenMap.put("%=", MOD_ASSIGN);
        tokenMap.put("==", EQUAL);
        tokenMap.put("===", ABSOLUTE_EQUAL);
        tokenMap.put("!=", NOT_EQUAL);
        tokenMap.put("!==", ABSOLUTE_NOT_EQUAL);
        tokenMap.put(">", GREATER);
        tokenMap.put("<", LESS);
        tokenMap.put(">=", GREATER_EQUAL);
        tokenMap.put("<=", LESS_EQUAL);
        tokenMap.put("&&", AND);
        tokenMap.put("||", OR);
        tokenMap.put("!", NOT);
        tokenMap.put("?", QUESTION);
        tokenMap.put(":", COLON);
        tokenMap.put(";", SEMI);
        tokenMap.put(",", COMMA);
        tokenMap.put(".", DOT);
        tokenMap.put("(", LEFT_SMALL_BRACKET);
        tokenMap.put("[", LEFT_MID_BRACKET);
        tokenMap.put("{", LEFT_LARGE_BRACKET);
        tokenMap.put(")", RIGHT_SMALL_BRACKET);
        tokenMap.put("]", RIGHT_MID_BRACKET);
        tokenMap.put("}", RIGHT_LARGE_BRACKET);
    }
}
