package com.hdu.common;

import java.util.HashMap;
import java.util.Map;

public class PythonTokens {

    // 关键字
    public static final byte FALSE = 0;
    public static final byte NONE = 1;
    public static final byte TRUE = 2;
    public static final byte AND = 3;
    public static final byte AS = 4;
    public static final byte ASSERT = 5;
    public static final byte BREAK = 6;
    public static final byte CLASS = 7;
    public static final byte CONTINUE = 8;
    public static final byte DEF = 9;
    public static final byte DEL = 10;
    public static final byte ELIF = 11;
    public static final byte ELSE = 12;
    public static final byte EXCEPT = 13;
    public static final byte FINALLY = 14;
    public static final byte FOR = 15;
    public static final byte FROM = 16;
    public static final byte GLOBAL = 17;
    public static final byte IF = 18;
    public static final byte IMPORT = 19;
    public static final byte IN = 20;
    public static final byte IS = 21;
    public static final byte LAMBDA = 22;
    public static final byte NONLOCAL = 23;
    public static final byte NOT = 24;
    public static final byte OR = 25;
    public static final byte PASS = 26;
    public static final byte RAISE = 27;
    public static final byte RETURN = 28;
    public static final byte TRY = 29;
    public static final byte WHILE = 30;
    public static final byte WITH = 31;
    public static final byte YIELD = 32;
    public static final byte IDENTIFIER = 33;
    public static final byte DIGIT = 34;
    public static final byte LEFT_PAREN = 35;
    public static final byte RIGHT_PAREN = 36;
    public static final byte LEFT_BRACKET = 37;
    public static final byte RIGHT_BRACKET = 38;
    public static final byte DOT = 39;

    public static final byte BOUND_LEFT = 40;
    public static final byte BOUND_RIGHT = 41;

    public static final byte PLUS = 42;
    public static final byte MINUS = 43;
    public static final byte STAR = 44;
    public static final byte DIV = 45;
    public static final byte MOD = 46;
    public static final byte EXP = 47;
    public static final byte DIV2 = 48;
    public static final byte EQUAL = 49;
    public static final byte NOT_EQUAL = 50;
    public static final byte GREATER = 51;
    public static final byte LESS = 52;
    public static final byte GREATER_EQUAL = 53;
    public static final byte LESS_EQUAL = 54;
    public static final byte ASSIGN = 55;
    public static final byte PLUS_ASSIGN = 56;
    public static final byte MINUS_ASSIGN = 57;
    public static final byte STAR_ASSIGN = 58;
    public static final byte DIV_ASSIGN = 59;
    public static final byte MOD_ASSIGN = 60;
    public static final byte EXP_ASSIGN = 61;
    public static final byte DIV2_ASSIGN = 62;
    public static final byte BIT_AND = 63;
    public static final byte BIT_OR = 64;
    public static final byte BIT_CARET = 65;
    public static final byte BIT_TILDE = 66;
    public static final byte LEFT_SHIFT = 67;
    public static final byte RIGHT_SHIFT = 68;
    public static final byte COMMA = 69;
    public static final byte COLON = 70;
    public static final byte LEFT_BRACE = 71;
    public static final byte RIGHT_BRACE = 72;


    public static Map<String, Byte> tokenMap = new HashMap<>();

    static {
        tokenMap.put("False", FALSE);
        tokenMap.put("None", NONE);
        tokenMap.put("True", TRUE);
        tokenMap.put("and", AND);
        tokenMap.put("as", AS);
        tokenMap.put("assert", ASSERT);
        tokenMap.put("break", BREAK);
        tokenMap.put("class", CLASS);
        tokenMap.put("continue", CONTINUE);
        tokenMap.put("def", DEF);
        tokenMap.put("del", DEL);
        tokenMap.put("elif", ELIF);
        tokenMap.put("else", ELSE);
        tokenMap.put("except", EXCEPT);
        tokenMap.put("finally", FINALLY);
        tokenMap.put("for", FOR);
        tokenMap.put("from", FROM);
        tokenMap.put("global", GLOBAL);
        tokenMap.put("if", IF);
        tokenMap.put("import", IMPORT);
        tokenMap.put("in", IN);
        tokenMap.put("is", IS);
        tokenMap.put("lambda", LAMBDA);
        tokenMap.put("nonlocal", NONLOCAL);
        tokenMap.put("not", NOT);
        tokenMap.put("or", OR);
        tokenMap.put("pass", PASS);
        tokenMap.put("raise", RAISE);
        tokenMap.put("return", RETURN);
        tokenMap.put("try", TRY);
        tokenMap.put("while", WHILE);
        tokenMap.put("with", WITH);
        tokenMap.put("yield", YIELD);
        tokenMap.put("(", LEFT_PAREN);
        tokenMap.put(")", RIGHT_PAREN);
        tokenMap.put("[", LEFT_BRACKET);
        tokenMap.put("]", RIGHT_BRACKET);
        tokenMap.put("{", LEFT_BRACE);
        tokenMap.put("}", RIGHT_BRACE);
        tokenMap.put("+", PLUS);
        tokenMap.put("-", MINUS);
        tokenMap.put("*", STAR);
        tokenMap.put("/", DIV);
        tokenMap.put("%", MOD);
        tokenMap.put("**", EXP);
        tokenMap.put("//", DIV2);
        tokenMap.put("==", EQUAL);
        tokenMap.put("!=", NOT_EQUAL);
        tokenMap.put(">", GREATER);
        tokenMap.put("<", LESS);
        tokenMap.put(">=", GREATER_EQUAL);
        tokenMap.put("<=", LESS_EQUAL);
        tokenMap.put("=", ASSIGN);
        tokenMap.put("+=", PLUS_ASSIGN);
        tokenMap.put("-=", MINUS_ASSIGN);
        tokenMap.put("*=", STAR_ASSIGN);
        tokenMap.put("/=", DIV_ASSIGN);
        tokenMap.put("%=", MOD_ASSIGN);
        tokenMap.put("**=", EXP_ASSIGN);
        tokenMap.put("//=", DIV2_ASSIGN);
        tokenMap.put("&", BIT_AND);
        tokenMap.put("|", BIT_OR);
        tokenMap.put("^", BIT_CARET);
        tokenMap.put("~", BIT_TILDE);
        tokenMap.put("<<", LEFT_SHIFT);
        tokenMap.put(">>", RIGHT_SHIFT);
        tokenMap.put(".", DOT);
        tokenMap.put(",", COMMA);
        tokenMap.put(":", COLON);
    }
}
